### ISSUE TITLE
[BUG] Awtric icon install error

### ISSUE THREAD

**Issue by adrienrichmond** [Blueforcer/awtrix3#537] opened 2024-04-22 09:27 UTC
# Bug report

## Describe the bug

When I try to install an impossible Metric icon: "This ID doesn't exist"

Add a description of the bug. Detail the expected behaviour in contrast with the behaviour you're observing.

## Additional information

- Devices involved:
  - Model: Ulanzi TC001
  - awtrix3 version: [ eg. v0.96 ]

## To Reproduce

Go to the website pannel < push id < error

## Expected behavior

Error go check the screen

## Screenshots

![image](https://github.com/Blueforcer/awtrix3/assets/95107131/3155e63a-3f63-403c-9a21-9abec4deef9e)

## Logs

```text
(optional) Add relevant logs which could help tackle the problem.
```

**Comment by Blueforcer** [comment] 2024-04-22 23:04
https://github.com/Blueforcer/awtrix3/issues/362#issuecomment-2069952551

**Comment by serfin64** [comment] 2024-05-16 08:29
Awtrix version 0.96

![Icons](https://github.com/Blueforcer/awtrix3/assets/156530596/17712b6a-5e3f-42f2-8c8d-bb50ccf31b63)

Icons do not load - it says there is no such identifier


You cannot load icons and sounds into the Icons and Melodies folders through the File Manager. Uploaded only to the root directory

![Awtrix_0,96](https://github.com/Blueforcer/awtrix3/assets/156530596/50fb050e-5c23-4dad-b478-a9b9d9302929)

**Comment by Blueforcer** [comment] 2024-05-16 08:51
You can, just make sure the Path at the top is correct set to /ICONS/

**Comment by TheCBiker** [comment] 2024-06-21 22:02
The error can be caused by an adblocker or pihole. Try deactivating them temporarily.

**Comment by Blueforcer** [comment] 2024-06-21 22:04
One bug is fixed in the latest beta. You can find it in my discord channel

**Closed** 2024-12-24 12:03 UTC
Labels: bug
