### ISSUE TITLE
Automatic boot on "power by cable"

### ISSUE THREAD

**Issue by B42S** [Blueforcer/awtrix3#522] opened 2024-03-30 11:33 UTC
# Automatic boot on "USB Power".

### Describe the solution / feature you'd like
Have TC001 boot up when USB power is applied. This is especially interesting when in has switched off due to empty akku.

### Additional context
I'm using Awtrix 3 on several TC001 as status displays for my smart home.
They are connected to USB permanently.
To save energy during the night, the house is in deep sleep mode and among others the power of the TC001 is switched off and the TC001 are sent to sleep mode (display off. When the akku is empty during the night, the TC001 power down.
In the morning the house wakes up and the USB power for the TC001 is restored. In this case I'd like to have the TC001s boot up automatically.

A switch in the dev.json would be great if possible.

Thank you in advance and a big thumbs up for your great work!
B

**Comment by Blueforcer** [comment] 2024-03-30 11:42
Duplicate of #516 and #520

**Closed** 2024-03-30 11:42 UTC
Labels: feature request

**Comment by B42S** [comment] 2024-03-30 11:49
For that!
Thank you and have a happy Easter Weekend.

Bernhard
